### ISSUE TITLE
PEP621 - Switch to `pyproject.toml`

### ISSUE THREAD

**Issue by dmohns** [EnAccess/OpenPAYGO#25]
The `openpaygo-token` package currently uses the legacy `setup.py` build system. It would be great to switch to `pyproject.toml` instead as discussed in [PEP621](https://peps.python.org/pep-0621/).

Our `pyproject.toml` could be something like this

```toml
[project]
name = "openpaygo_token"
version = "2.2.1"
readme = "README.md"
license = {file = "LICENSE"}

[project.urls]
homepage = "https://enaccess.org/materials/openpaygotoken/"
documentation = "https://github.com/EnAccess/OpenPAYGO-Token/tree/main/documentation"
repository = "https://github.com/EnAccess/OpenPAYGO-Token"
changelog = "https://github.com/EnAccess/OpenPAYGO-Token/releases"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
```
